import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import localFont from "next/font/local";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const mona = localFont({
  src: "../fonts/monasans.ttf",
  display: "swap",
  variable: "--font-mona",
});
const clash = localFont({
  src: "../fonts/clashdisplay.ttf",
  display: "swap",
  variable: "--font-clash",
});
const satoshi = localFont({
  src: "../fonts/satoshi.ttf",
  display: "swap",
  variable: "--font-satoshi",
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={satoshi.className+"dark"}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
